### ISSUE TITLE
Tracing RPC

### ISSUE THREAD

**Issue by frisitano** [scroll-tech/reth#51]
# Overview
We need to introduce a tracing RPC such that we can generate block traces for our proving backend. For the implementation, we need to decide which proving backend and state representation we will use. We can leverage reth's `extend_rpc_modules` API on the node builder to add these rpc methods. This issue depends on resolution of #50.

# Considerations
Reth only stores the latest state trie nodes in the database. As such if we want to produce traces for historical blocks this requires a rollback of state. For blocks far in the past this would require significant memory overhead. As such we may want to persist state witnesses in an external database such that they can be easily served and pruned. See [`zeth`](https://github.com/fractal-zkp/zeth/tree/main) for an example of how this can be done.

**Comment by frisitano** [comment]
We will be targeting support for a novel risc-V based zkVM as our proving backend. As such we do not need to make modifications to support the existing halo-based prover. Some considerations:

- reth already provides a `debug_executionWitness` which provides an `ExecutionWitness` containing the trie witness and codes required for block execution.
- The `ExecutionWitness` does not include historical block hashes (or blocks) and as such invocation of the `BLOCKHASH` opcode may be problematic.
- Reth only stores a single instance of the latest trie data in storage and as such generating witnesses far from the head could carry significant overhead.

**Comment by lispc** [comment]
scroll-evm changes the behavior of `BLOCKHASH`, actually it is not real blockchain, but sha3(chain_id || block_number).  So real historical block hashes not needed actually.

We are integrate with debug_executionWitness currently.  We think it should be enough.  In short, we need (1) block context info like block num / basefee etc (2) txs (3) all accessed trie nodes (with preimages if leaf nodes), and trie sibling proofs (4) all accessed bytecodes. As i know they are all provided inside debug_executionWitness.

We prefer debug_executionWitness since it is initially proposed by geth team, and first implemented by reth team. It is much "standard" than our old trace format. Even we use our old trace format, we need to redesign around the l1 MPT changes.

**Comment by frisitano** [comment]
> scroll-evm changes the behavior of `BLOCKHASH`, actually it is not real blockchain, but sha3(chain_id || block_number). So real historical block hashes not needed actually.
> 
> We are integrate with debug_executionWitness currently. We think it should be enough. In short, we need (1) block context info like block num / basefee etc (2) txs (3) all accessed trie nodes (with preimages if leaf nodes), and trie sibling proofs (4) all accessed bytecodes. As i know they are all provided inside debug_executionWitness.
> 
> We prefer debug_executionWitness since it is initially proposed by geth team, and first implemented by reth team. It is much "standard" than our old trace format. Even we use our old trace format, we need to redesign around the l1 MPT changes.

That's good. To conclude, no additional work is required to support tracing and proving. You can leverage the pre-existing RPC methods to fetch the witness data.

**Comment by frisitano** [comment]
Given that no additional data is required for the prover witness we will close this issue.
